name: Build
run-name: Building project...
on: 
  workflow_run:
    workflows: [Lint]
    types: [completed]
jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checking out repository...
        uses: actions/checkout@v4
      - name: Installing dependencies...
        run: npm i
      - name: Building project...
        run: npm run build
